### ISSUE TITLE
Application segfaults under linux mint 17.1

### ISSUE THREAD

**Issue by dgets** [jaromil/HasciiCam#1]
Utilizing a 64 bit machine running Linux Mint 17.1 (64-bit), and a USB Logitech camera, I am unable to run the application without segfaulting.  I have turned on core dumps and have one available from this particular issue, if you are in need of one.  Please let me know if there is any more information that I can provide to you that can help with this issue; I would really like to see this working on Linux Mint with this hardware; I have a BBS that I'd very much like to add _hasciicam_ functionality to.

More than happy to provide that core dump or anything else you can point me at.  Feel free to contact me here; I try to check my notifications at least every other day.

**Comment by jaromil** [comment]
do you have the specs of the usb webcam? something to take out with v4l2utils or so

a good try is also to use another webcam and see how it goes

**Comment by dgets** [comment]
The webcam is a Logitech 'golfball' one; here's what _lsusb_ has to say about it:
`Bus 005 Device 003: ID 046d:08d7 Logitech, Inc. QuickCam Communicate STX`

_qv4l2_ is telling me that it's using driver **gspca_zc3xx** via _/dev/video0_, utilizing bus _usb-0000:00:1a.2-1_ (does that conflict with the _lsusb_ information?).  Card lists _USB Camera (046d:08d7)_.

I'm afraid I don't really have another cam to be testing with right now.  I'll talk to some people and see if I can't get my hands on one to work with, though.

TIA and let me know if there's anything else you need from me.

**Comment by jaromil** [comment]
I dont remember the way, but it should be possible with some v4l2 utility to find out the color spaces supported like yuv422 etc. as well the grabbing sizes but that shouldn't be a problem

**Comment by jaromil** [comment]
This issue is outdated and lacks detail, hence closed.
