### ISSUE TITLE
POS36-C

### ISSUE THREAD

**Issue by alcir** [jaromil/HasciiCam#8]
I'm not a developer/programmer. But this is the power of free software, meh.
So, running `rpmlint` versus the RPM package I created, it complaints about: [POS36-C]( https://wiki.sei.cmu.edu/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges)
<pre>
hasciicam.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/hasciicam
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
</pre>
As said I'm not a C programmer or so, but using these lines:
     
    637   setgroups(0, NULL);
    638   setgid(gid);
    649   setuid(uid);

instead of

    637   setuid (uid);
    638   setgid (gid);

hasciicam still works 😅 and `rpmlint` is happy.

**Comment by jaromil** [comment]
Thanks! it seems sane to use setgroups and drop all ancillary groups esp. since we permanently drop the privileges there.

**Comment by jaromil** [comment]
fixed in 12200d134b348a47e613efb2944e825697206cd7
