### ISSUE TITLE
Incorrect FSF address in the license file

### ISSUE THREAD

**Issue by alcir** [jaromil/HasciiCam#9]
This has nothing to do with the code.
Againg `rpmlint` 😅
<pre>
hasciicam.x86_64: E: incorrect-fsf-address /usr/share/licenses/hasciicam/COPYING
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.
</pre>
Indeed, the GPL license from the [GNU web](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html) site states:
<pre>
Copyright (C) 1989, 1991 Free Software Foundation, Inc.  
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
</pre>
While in the mentioned COPYING file:
<pre>
Copyright (C) 1989, 1991 Free Software Foundation, Inc.
59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
</pre>

**Comment by jaromil** [comment]
oh yes I had this elsewhere, they moved...
